### ISSUE TITLE
Encoding issue in Ruby 1.9.2

### ISSUE THREAD

**Issue by mantas** [nmerouze/machinist_mongo#8]
I'm running my application in Rails 3.0 / Ruby 1.9.2 stack under Passenger. When I started it with machinist_mongo (from machinist2 branch) installed, it didn't like non-ascii characters in gemspec file for some reason. Removing non-ascii characters from .gemspec fixed the problem.

**Comment by nmerouze** [comment]
My name is causing too much troubling, I'm going to remove the non-ascii characters.

**Comment by nmerouze** [comment]
pushed

**Comment by mantas** [comment]
Thanks. And thanks for the nice gem too!
